_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 2
codebook_loss_weight:
    value: 1
codebook_size:
    value: 512
commitment_beta:
    value: 0.25
data_path:
    value: datasets/Phoenix14T
device:
    value: cuda
flow_dim:
    value: 2
flow_stride:
    value: 2
landmark_dim:
    value: 129
learning_rate:
    value: 0.001
llm_name:
    value: meta-llama/Llama-3.2-1B
max_frames:
    value: 256
num_epochs:
    value: 2
num_fusion_blocks:
    value: 2
val_split_ratio:
    value: 0.1
visual_dim:
    value: 768
